# Generated by Django 3.0 on 2019-12-11 09:51

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ActionPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=100, verbose_name='app')),
                ('codename', models.CharField(max_length=100, verbose_name='codename')),
                ('view', models.CharField(max_length=100, verbose_name='view')),
                ('method', models.CharField(choices=[('GET', 'get'), ('POST', 'post'), ('PUT', 'put'), ('DELETE', 'delete')], max_length=8, verbose_name='method')),
                ('desc', models.CharField(max_length=255, verbose_name='desc')),
                ('groups', models.ManyToManyField(blank=True, related_name='action_permissions', related_query_name='action_permission', to='auth.Group', verbose_name='groups')),
                ('users', models.ManyToManyField(blank=True, related_name='action_permissions', related_query_name='action_permission', to=settings.AUTH_USER_MODEL, verbose_name='users')),
            ],
            options={
                'verbose_name': 'action_permission',
                'verbose_name_plural': 'action_permission',
                'ordering': ('app', 'view', 'codename'),
                'unique_together': {('app', 'codename')},
            },
        ),
    ]
